### PR TITLE
Renderer: implement basic font rendering

### PR DESCRIPTION
**Pull request by Eskpil**
**WIP**

What is there so far: 

-  glfw window in the terminal app
- some code that i thought would work in renderer/text.*

Goals

- glfw window that works [check]
- font rendering [not working, yet]

### CODE REVIEW

**Comment by Eskpil** [comment]
Why include headers of the renderer relative? Meson is already capable of finding the headers of a library.

**Comment by msal4** [comment]
> Why include headers of the renderer relative? Meson is already capable of finding the headers of a library.

I know it's not the best solution but for some reason meson wasn't able to find `glad/glad.h` so i did a relative include.

**Comment by Eskpil** [comment]
> > Why include headers of the renderer relative? Meson is already capable of finding the headers of a library.
> 
> I know it's not the best solution but for some reason meson wasn't able to find `glad/glad.h` so i did a relative include.

You can install the subdirectory as done in include/meson.build. I would personally like it if glad is nested under the renderer. So you will avoid any conflicts with other developers software.

**Comment by Eskpil** [comment]
I would also like the mention that i am working on a solution that will allow us to nest all our headers in maren/ so we will avoid all possible conflicts.

**Comment by Eskpil** [comment]
I am also at the stage of a segfault or a system crash. My recommendation is just scrapping the code and starting all over again.

**Pull request closed without merging**
